# Generated by Django 4.1.1 on 2022-09-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='phoneArea',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneArea',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
